version: '2'

volumes:
  postgres_data_dev: {}

services:

  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile-app
    environment:
      - DATABASE_URL=postgres://user_test:password_test@postgres/database_test
      - SECRET_KEY=verysecret
      - DEBUG=true
    depends_on:
      - postgres
    volumes:
      - ../../src:/app/src
      - ../../frontend:/app/frontend
    ports:
      - 0.0.0.0:8000:8000
    command: >-
      /bin/bash -c "
      /app/wait-for.sh postgres:5432 --timeout=60 &&
      cd /app/src/ &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user_test
      - POSTGRES_PASSWORD=password_test
      - POSTGRES_DB=database_test