FROM python:3.6.5-jessie

ADD src /app/src/
ADD requirements /app/requirements/
ADD Makefile /app/
ADD tox.ini /app/
ADD docker/wait-for.sh /app/

RUN pip install -r /app/requirements/requirements.txt