# Generated by Django 2.0.4 on 2018-04-18 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20180418_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 18, 6, 22, 3, 214672)),
        ),
    ]
